name: CI/CD Pipeline

on:
  push:
    branches:
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and test
        run:  | # Replace these commands with your build and test scripts
           echo "Building and testing your application..."

      - name: Deploy to Jenkins
        uses: jenkinsci/github-plugin@2
        with:
         url: http://localhost:9090/
         user: dm_19
         token: 11ee720f6c85d99084d5723f500615c3de
         job: jenkins-git # Replace with your Jenkins job name
      - name: Trigger Jenkins Job
        run: |
         curl -X POST http://localhost:9090/buildByToken/buildWithParameters?job=jenkins-git&token=11ee720f6c85d99084d5723f500615c3de
